### PR TITLE
Add TSLint

### LINKED ISSUE #93: Add proper linting
Add linting to the project

### PR DESCRIPTION
**Pull request by mattwilson1024**
Resolves #93.

This PR adds linting (using TSLint) to the project.

This can be tuned to taste - I tried to strike a balance between tidying up the code based on the the linting output, but also avoiding adjusting functionality or straying too far from the author's code style. 

The initial set of rules extend the default `tslint:recommended` set, but with a number of rules disabled or adjusted in order to avoid the linter lighting up the code in a sea of red. I would recommend looking through each of these rules in the [TSLint docs](https://palantir.github.io/tslint/rules/) to understand what they do and, if they could add value, re-enabling them and adjusting the code to suit.

I also included `tslint-eslint-rules` which provides a helpful additional rule, `ter-indent`. This will highlight any indentation issues. I set the indentation level to 4 since that seems to match up with the indentation in the code.

### CODE REVIEW

**Comment by Scoombe** [comment]
@mattwilson1024  Awesome thanks for the changes! I'm going to have a look at the travis config to add the linting.

**Comment by Scoombe** [comment]
@mattwilson1024  Also is it worth putting the linting on the test file. As I don't think the lint rule is picking up the test file?

**Comment by mattwilson1024** [comment]
@Scoombe - you're welcome.  Nice addition with the `lint-fix` rule 👍  I've submitted another PR #137 which includes the test file in the linting as you suggested.

**Comment by Scoombe** [comment]
@mattwilson1024  would you be interested in looking at the other repository that has some similar issues?
[scoombe/wpmtest](http://github.com/scoombe/wpmtest)

**Pull request merged**
